const SERVER_CLIENT_PORT 	= '3000'
const SERVER_CLIENT_IP 		= 'http://3.15.223.31'
// const SERVER_CLIENT_PORT = '708'
// const SERVER_CLIENT_IP = 'http://172.16.202.68'
const SERVER_API_PREFIX 	= ''
const SERVER_CLIENT_ADDRESS = `${SERVER_CLIENT_IP}:${SERVER_CLIENT_PORT}`
const SERVER_API_ADDRESS 	= `${SERVER_CLIENT_ADDRESS}`

export default {
   SERVER_CLIENT_PORT,
   SERVER_CLIENT_IP,
   SERVER_CLIENT_ADDRESS,
   SERVER_API_ADDRESS
}